## QCT compile option
# enable sequence: e.g., msm8994
#    1. $ANDROID/device/htc/$TARGET_PRODUCT/BoardConfig.mk
#    2. $ANDROID/device/qcom/$TARGET_BOARD_PLATFORM/BoardConfig.mk
#       -  include $(QCPATH)/common/$TARGET_BOARD_PLATFORM/BoardConfigVendor.mk
#    3. $ANDROID/vendor/qcom/proprietary/common/$TARGET_BOARD_PLATFORM/BoardConfigVendor.mk

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_EXTN_RESAMPLER)),true)
#HTC_INTERNAL_CDEFS += -DQTI_RESAMPLER
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_COMPRESS_VOIP)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_COMPRESS_VOIP_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_EXTN_FORMATS)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_FORMATS_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_FM)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_FM_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_HDMI_SPK)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_HDMI_SPK_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_INCALL_MUSIC)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_INCALL_MUSIC_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_MULTIPLE_TUNNEL)), true)
#HTC_INTERNAL_CDEFS += -DMULTIPLE_OFFLOAD_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_PCM_OFFLOAD)),true)
#HTC_INTERNAL_CDEFS += -DPCM_OFFLOAD_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_PCM_OFFLOAD_24)),true)
#HTC_INTERNAL_CDEFS += -DPCM_OFFLOAD_ENABLED_24
#endif

ifeq ($(strip $(AUDIO_FEATURE_ENABLED_PROXY_DEVICE)),true)
HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_AFE_PROXY_ENABLED
endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_SSR)),true)
#HTC_INTERNAL_CDEFS += -DAUDIO_EXTN_SSR_ENABLED
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_VOICE_CONCURRENCY)),true)
#HTC_INTERNAL_CDEFS += -DVOICE_CONCURRENCY
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_RECORD_PLAY_CONCURRENCY)),true)
#HTC_INTERNAL_CDEFS += -DRECORD_PLAY_CONCURRENCY
#endif

#ifeq ($(strip $(AUDIO_FEATURE_ENABLED_HDMI_PASSTHROUGH)),true)
#HTC_INTERNAL_CDEFS += -DHDMI_PASSTHROUGH_ENABLED
#endif
